# Generated by Django 4.2.4 on 2023-09-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotegenius', '0003_alter_supplierproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='purchase_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
